name: Test comment automatiser les commits sur GitHub

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'  # Runs daily at midnight

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make changes
      run: |
        # Your script or commands to modify files
        echo "commit 0 */3 * * * Some changes" >> file.txt

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "commit 0 */3 * * *"
        branch: main
